// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwiqpwvdvixnkmwdangq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3aXFwd3Zkdml4bmttd2RhbmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjY4MDgsImV4cCI6MjA2NTQwMjgwOH0.o3qhr3vizDOzc8XdC1eeIWFyavGAQAoKBXlwjLQ4zrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);